### ISSUE TITLE
Build on windows

### ISSUE THREAD

**Issue by itubetw** [chillerbot/chillerbot-ng#8]
![image](https://user-images.githubusercontent.com/91550686/174406902-8617d13c-2cae-417e-9c34-98a5fe692640.png)

like we see its not working cause an dll not found, if i upload the dll happends that:

![image](https://user-images.githubusercontent.com/91550686/174406963-4288b245-910f-4e5f-99ec-b4ec98cf90ae.png)

**Comment by ChillerDragon** [comment]
This client is deprecated just compile ddnet or chillerbot-ux with `HEADLESS_CLIENT=ON`

**Comment by itubetw** [comment]
> This client is deprecated just compile ddnet or chillerbot-ux with `HEADLESS_CLIENT=ON`

where i find  `HEADLESS_CLIENT=ON` i searched a bit but find nothing lul

**Comment by ChillerDragon** [comment]
> > This client is deprecated just compile ddnet or chillerbot-ux with `HEADLESS_CLIENT=ON`
> 
> where i find `HEADLESS_CLIENT=ON` i searched a bit but find nothing lul

It is a cmake option. I only linux pass it in like this when running the cmake command.

`cmake -DHEADLESS_CLIENT=ON ..`

In visual studio there is probably a setting in the UI

**Comment by itubetw** [comment]
> > > This client is deprecated just compile ddnet or chillerbot-ux with `HEADLESS_CLIENT=ON`
> > 
> > where i find `HEADLESS_CLIENT=ON` i searched a bit but find nothing lul
> 
> It is a cmake option. I only linux pass it in like this when running the cmake command.
> 
> `cmake -DHEADLESS_CLIENT=ON ..`
> 
> In visual studio there is probably a setting in the UI

Give tuto when free time pls :D
